// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateGameHandlerFunc turns a function with the right signature into a create game handler
type CreateGameHandlerFunc func(CreateGameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateGameHandlerFunc) Handle(params CreateGameParams) middleware.Responder {
	return fn(params)
}

// CreateGameHandler interface for that can handle valid create game params
type CreateGameHandler interface {
	Handle(CreateGameParams) middleware.Responder
}

// NewCreateGame creates a new http.Handler for the create game operation
func NewCreateGame(ctx *middleware.Context, handler CreateGameHandler) *CreateGame {
	return &CreateGame{Context: ctx, Handler: handler}
}

/*CreateGame swagger:route POST /drop_token createGame

CreateGame create game API

*/
type CreateGame struct {
	Context *middleware.Context
	Handler CreateGameHandler
}

func (o *CreateGame) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateGameParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
