// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMoveParams creates a new GetMoveParams object
// no default values defined in spec.
func NewGetMoveParams() GetMoveParams {

	return GetMoveParams{}
}

// GetMoveParams contains all the bound params for the get move operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetMove
type GetMoveParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	GameID string
	/*
	  Required: true
	  In: path
	*/
	MoveNumber int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetMoveParams() beforehand.
func (o *GetMoveParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rGameID, rhkGameID, _ := route.Params.GetOK("gameId")
	if err := o.bindGameID(rGameID, rhkGameID, route.Formats); err != nil {
		res = append(res, err)
	}

	rMoveNumber, rhkMoveNumber, _ := route.Params.GetOK("move_number")
	if err := o.bindMoveNumber(rMoveNumber, rhkMoveNumber, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindGameID binds and validates parameter GameID from path.
func (o *GetMoveParams) bindGameID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.GameID = raw

	return nil
}

// bindMoveNumber binds and validates parameter MoveNumber from path.
func (o *GetMoveParams) bindMoveNumber(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("move_number", "path", "int64", raw)
	}
	o.MoveNumber = value

	return nil
}
