// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// GetMoveURL generates an URL for the get move operation
type GetMoveURL struct {
	GameID     string
	MoveNumber int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetMoveURL) WithBasePath(bp string) *GetMoveURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetMoveURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetMoveURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/drop_token/{gameId}/moves/{move_number}"

	gameID := o.GameID
	if gameID != "" {
		_path = strings.Replace(_path, "{gameId}", gameID, -1)
	} else {
		return nil, errors.New("GameID is required on GetMoveURL")
	}

	moveNumber := swag.FormatInt64(o.MoveNumber)
	if moveNumber != "" {
		_path = strings.Replace(_path, "{move_number}", moveNumber, -1)
	} else {
		return nil, errors.New("MoveNumber is required on GetMoveURL")
	}

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetMoveURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetMoveURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetMoveURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetMoveURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetMoveURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetMoveURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
