// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetGameHandlerFunc turns a function with the right signature into a get game handler
type GetGameHandlerFunc func(GetGameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetGameHandlerFunc) Handle(params GetGameParams) middleware.Responder {
	return fn(params)
}

// GetGameHandler interface for that can handle valid get game params
type GetGameHandler interface {
	Handle(GetGameParams) middleware.Responder
}

// NewGetGame creates a new http.Handler for the get game operation
func NewGetGame(ctx *middleware.Context, handler GetGameHandler) *GetGame {
	return &GetGame{Context: ctx, Handler: handler}
}

/*GetGame swagger:route GET /drop_token/{gameId} getGame

GetGame get game API

*/
type GetGame struct {
	Context *middleware.Context
	Handler GetGameHandler
}

func (o *GetGame) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetGameParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
