// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetGameParams creates a new GetGameParams object
// no default values defined in spec.
func NewGetGameParams() GetGameParams {

	return GetGameParams{}
}

// GetGameParams contains all the bound params for the get game operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetGame
type GetGameParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	GameID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetGameParams() beforehand.
func (o *GetGameParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rGameID, rhkGameID, _ := route.Params.GetOK("gameId")
	if err := o.bindGameID(rGameID, rhkGameID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindGameID binds and validates parameter GameID from path.
func (o *GetGameParams) bindGameID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.GameID = raw

	return nil
}
