// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "98point6DropToken/models"
)

// GetAllMovesOKCode is the HTTP code returned for type GetAllMovesOK
const GetAllMovesOKCode int = 200

/*GetAllMovesOK OK

swagger:response getAllMovesOK
*/
type GetAllMovesOK struct {

	/*
	  In: Body
	*/
	Payload *models.AllMoves `json:"body,omitempty"`
}

// NewGetAllMovesOK creates GetAllMovesOK with default headers values
func NewGetAllMovesOK() *GetAllMovesOK {

	return &GetAllMovesOK{}
}

// WithPayload adds the payload to the get all moves o k response
func (o *GetAllMovesOK) WithPayload(payload *models.AllMoves) *GetAllMovesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all moves o k response
func (o *GetAllMovesOK) SetPayload(payload *models.AllMoves) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllMovesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAllMovesBadRequestCode is the HTTP code returned for type GetAllMovesBadRequest
const GetAllMovesBadRequestCode int = 400

/*GetAllMovesBadRequest Malformed Request

swagger:response getAllMovesBadRequest
*/
type GetAllMovesBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.MalformedRequest `json:"body,omitempty"`
}

// NewGetAllMovesBadRequest creates GetAllMovesBadRequest with default headers values
func NewGetAllMovesBadRequest() *GetAllMovesBadRequest {

	return &GetAllMovesBadRequest{}
}

// WithPayload adds the payload to the get all moves bad request response
func (o *GetAllMovesBadRequest) WithPayload(payload *models.MalformedRequest) *GetAllMovesBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all moves bad request response
func (o *GetAllMovesBadRequest) SetPayload(payload *models.MalformedRequest) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllMovesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAllMovesNotFoundCode is the HTTP code returned for type GetAllMovesNotFound
const GetAllMovesNotFoundCode int = 404

/*GetAllMovesNotFound Game not found

swagger:response getAllMovesNotFound
*/
type GetAllMovesNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.MalformedRequest `json:"body,omitempty"`
}

// NewGetAllMovesNotFound creates GetAllMovesNotFound with default headers values
func NewGetAllMovesNotFound() *GetAllMovesNotFound {

	return &GetAllMovesNotFound{}
}

// WithPayload adds the payload to the get all moves not found response
func (o *GetAllMovesNotFound) WithPayload(payload *models.MalformedRequest) *GetAllMovesNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all moves not found response
func (o *GetAllMovesNotFound) SetPayload(payload *models.MalformedRequest) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllMovesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
