// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	models "98point6DropToken/models"
)

// NewMakeMoveParams creates a new MakeMoveParams object
// no default values defined in spec.
func NewMakeMoveParams() MakeMoveParams {

	return MakeMoveParams{}
}

// MakeMoveParams contains all the bound params for the make move operation
// typically these are obtained from a http.Request
//
// swagger:parameters MakeMove
type MakeMoveParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	NewMove *models.NewMove
	/*
	  Required: true
	  In: path
	*/
	GameID string
	/*
	  Required: true
	  In: path
	*/
	PlayerID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewMakeMoveParams() beforehand.
func (o *MakeMoveParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.NewMove
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("newMove", "body"))
			} else {
				res = append(res, errors.NewParseError("newMove", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.NewMove = &body
			}
		}
	} else {
		res = append(res, errors.Required("newMove", "body"))
	}
	rGameID, rhkGameID, _ := route.Params.GetOK("gameId")
	if err := o.bindGameID(rGameID, rhkGameID, route.Formats); err != nil {
		res = append(res, err)
	}

	rPlayerID, rhkPlayerID, _ := route.Params.GetOK("playerId")
	if err := o.bindPlayerID(rPlayerID, rhkPlayerID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindGameID binds and validates parameter GameID from path.
func (o *MakeMoveParams) bindGameID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.GameID = raw

	return nil
}

// bindPlayerID binds and validates parameter PlayerID from path.
func (o *MakeMoveParams) bindPlayerID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.PlayerID = raw

	return nil
}
