// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// RemovePlayerHandlerFunc turns a function with the right signature into a remove player handler
type RemovePlayerHandlerFunc func(RemovePlayerParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RemovePlayerHandlerFunc) Handle(params RemovePlayerParams) middleware.Responder {
	return fn(params)
}

// RemovePlayerHandler interface for that can handle valid remove player params
type RemovePlayerHandler interface {
	Handle(RemovePlayerParams) middleware.Responder
}

// NewRemovePlayer creates a new http.Handler for the remove player operation
func NewRemovePlayer(ctx *middleware.Context, handler RemovePlayerHandler) *RemovePlayer {
	return &RemovePlayer{Context: ctx, Handler: handler}
}

/*RemovePlayer swagger:route DELETE /drop_token/{gameId}/{playerId} removePlayer

RemovePlayer remove player API

*/
type RemovePlayer struct {
	Context *middleware.Context
	Handler RemovePlayerHandler
}

func (o *RemovePlayer) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRemovePlayerParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
